<?php

namespace Database\Seeders;

use App\Models\InsuranceCompany;
use Illuminate\Database\Seeder;

class InsuranceCompaniesSeeder extends Seeder
{
    public function run(): void
    {
        $companies = $this->getCompanies();

        foreach ($companies as $company) {
            InsuranceCompany::firstOrCreate(
                ['name' => $company['name']],
                $company
            );
        }
    }

    private function getCompanies(): array
    {
        return [
            // === UNDERWRITERS ===
            [
                'name' => 'AIICO Insurance Plc',
                'company_type' => 'underwriter',
                'email' => 'info@aiiconsurance.com',
                'phone' => '+234 1 277 2900',
                'website' => 'https://www.aiiconsurance.com',
                'address' => 'AIICO Plaza, Plot 1, Block 1,Ipaja Road, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/001',
                'rc_number' => 'RC. 18741',
                'is_active' => true,
            ],
            [
                'name' => 'AXA Mansard Insurance Plc',
                'company_type' => 'underwriter',
                'email' => 'customer-service@axamansard.com',
                'phone' => '+234 1 270 7660',
                'website' => 'https://www.axamansard.com',
                'address' => 'AXA Mansard House, 14/15 Ajuda Street, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/002',
                'rc_number' => 'RC. 45829',
                'is_active' => true,
            ],
            [
                'name' => 'Leadway Assurance Company Ltd',
                'company_type' => 'underwriter',
                'email' => 'info@leadwayassurance.com',
                'phone' => '+234 1 461 9900',
                'website' => 'https://www.leadwayassurance.com',
                'address' => 'Michele OHouse,Plot 118,Igbariam Close,Abuja',
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/003',
                'rc_number' => 'RC. 4886',
                'is_active' => true,
            ],
            [
                'name' => 'Consolidated Hallmark Insurance Plc',
                'company_type' => 'underwriter',
                'email' => 'info@consolidatedhallmark.com',
                'phone' => '+234 1 631 3420',
                'website' => 'https://www.consolidatedhallmark.com',
                'address' => 'Consolidated Hallmark House, 24, Alhaji Olaniji Street, Off Joel Ogunbiyi Road, Ikeja, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/004',
                'rc_number' => 'RC. 45796',
                'is_active' => true,
            ],
            [
                'name' => 'NEM Insurance Plc',
                'company_type' => 'underwriter',
                'email' => 'info@nem-insurance.com',
                'phone' => '+234 1 291 8400',
                'website' => 'https://www.nem-insurance.com',
                'address' => 'NEM House, 67/68 Okwu Emeka Street, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/005',
                'rc_number' => 'RC. 22885',
                'is_active' => true,
            ],
            [
                'name' => 'Custodian and Allied Insurance Plc',
                'company_type' => 'underwriter',
                'email' => 'info@custodianinsurance.com',
                'phone' => '+234 1 280 2500',
                'website' => 'https://www.custodianinsurance.com',
                'address' => 'Custodian House, 16A, Oden Street, Off Adeniran Oguntosha Street, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/006',
                'rc_number' => 'RC. 16594',
                'is_active' => true,
            ],
            [
                'name' => 'Coronation Insurance Plc',
                'company_type' => 'underwriter',
                'email' => 'info@coronationinsurance.com',
                'phone' => '+234 1 342 0007',
                'website' => 'https://www.coronationinsurance.com',
                'address' => 'Coronation House, 8, Lugard Avenue, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/007',
                'rc_number' => 'RC. 58302',
                'is_active' => true,
            ],
            [
                'name' => 'Sanlam General Insurance Nigeria Ltd',
                'company_type' => 'underwriter',
                'email' => 'customerdesk@sanlam.com.ng',
                'phone' => '+234 1 277 4400',
                'website' => 'https://www.sanlam.com.ng',
                'address' => 'Sanlam House, 2-4 Wharf Road, Apapa, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/008',
                'rc_number' => 'RC. 1016',
                'is_active' => true,
            ],
            [
                'name' => 'Zenith General Insurance Co. Ltd',
                'company_type' => 'underwriter',
                'email' => 'info@zenithinsurance.com.ng',
                'phone' => '+234 1 278 2000',
                'website' => 'https://www.zenithinsurance.com.ng',
                'address' => 'Zenith Heights, 29/31 Gornon/Zion Road, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/009',
                'rc_number' => 'RC. 208675',
                'is_active' => true,
            ],
            [
                'name' => 'Niger Insurance Plc',
                'company_type' => 'underwriter',
                'email' => 'info@nigerinsurance.com',
                'phone' => '+234 8034020141',
                'website' => 'https://www.nigerinsurance.com',
                'address' => 'Niger Insurance House, Plot 38, Alhaja Kubrat Road, Ilorin',
                'city' => 'Ilorin',
                'state' => 'Kwara',
                'country' => 'Nigeria',
                'naicom_reg_number' => 'RN/010',
                'rc_number' => 'RC. 1332',
                'is_active' => true,
            ],

            // === BROKERS ===
            [
                'name' => 'Arthur J. Gallagher (Nigeria) Ltd',
                'company_type' => 'broker',
                'email' => 'nigeria@ajg.com',
                'phone' => '+234 1 460 3600',
                'website' => 'https://www.ajg.com/nigeria',
                'address' => 'Gallagher House, Plot 1688, Oyebanji Street, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/201',
                'is_active' => true,
            ],
            [
                'name' => 'Marsh Nigeria Limited',
                'company_type' => 'broker',
                'email' => 'enquiries@marsh.com',
                'phone' => '+234 1 460 5000',
                'website' => 'https://www.marsh.com/nigeria',
                'address' => 'The Civic Centre, 3rd Floor, 2-5 Oyebanji Street, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/202',
                'is_active' => true,
            ],
            [
                'name' => 'Stanbic IBTC Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'insurance@stanbicibtc.com',
                'phone' => '+234 1 295 7000',
                'website' => 'https://www.stanbicibtc.com',
                'address' => 'Stanbic IBTC Plaza, 2-5 Oyebanji Close, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/203',
                'is_active' => true,
            ],
            [
                'name' => 'Aon Risk Solutions Nigeria Ltd',
                'company_type' => 'broker',
                'email' => 'enquiries.ng@aon.com',
                'phone' => '+234 1 277 4300',
                'website' => 'https://www.aon.com/nigeria',
                'address' => 'Aon Nigeria House, 9th Floor, 51/57 Broad Street, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/204',
                'is_active' => true,
            ],
            [
                'name' => 'FBN Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'insurance.brokers@fbnquest.com',
                'phone' => '+234 1 274 3800',
                'website' => 'https://www.fbnquest.com',
                'address' => 'FBN Quest House, 12 Amodu Ojulari Way, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/205',
                'is_active' => true,
            ],
            [
                'name' => 'Access Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'info@accessbankgroup.com',
                'phone' => '+234 1 271 2000',
                'website' => 'https://www.accessbankgroup.com',
                'address' => 'Access Tower, Plot 366, Alexandra Avenue, Ikoyi, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/206',
                'is_active' => true,
            ],
            [
                'name' => 'Zenith Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'brokerage@zenithbank.com',
                'phone' => '+234 1 278 2000',
                'website' => 'https://www.zenithbank.com',
                'address' => 'Zenith Heights, 29/31 Gornon/Zion Road, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/207',
                'is_active' => true,
            ],
            [
                'name' => 'SCIB Nigeria Limited',
                'company_type' => 'broker',
                'email' => 'enquiries@scibng.com',
                'phone' => '+234 1 271 4188',
                'website' => 'https://www.scibng.com',
                'address' => 'SCIB House, Plot 15, 2nd Street, Off Commerce Road, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/208',
                'is_active' => true,
            ],
            [
                'name' => 'Unitrust Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'brokerage@unitrustng.com',
                'phone' => '+234 1 271 5400',
                'website' => 'https://www.unitrustng.com',
                'address' => 'Unitrust House, 57-68 Egbeda Layout, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/209',
                'is_active' => true,
            ],
            [
                'name' => 'NEM Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'brokerage@nem-insurance.com',
                'phone' => '+234 1 291 8400',
                'website' => 'https://www.nem-insurance.com/brokers',
                'address' => 'NEM House, 67/68 Okwu Emeka Street, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/210',
                'is_active' => true,
            ],
            [
                'name' => 'AIICO Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'brokerage@aiiconsurance.com',
                'phone' => '+234 1 277 2900',
                'website' => 'https://www.aiiconsurance.com/brokers',
                'address' => 'AIICO Plaza, Plot 1, Block 1, Ipaja Road, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/211',
                'is_active' => true,
            ],
            [
                'name' => 'GTI Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'info@gtimf.com',
                'phone' => '+234 803 456 7890',
                'website' => 'https://www.gtimf.com',
                'address' => 'GTI House, Plot 15, GTI Way, Owerri',
                'city' => 'Owerri',
                'state' => 'Imo',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/212',
                'is_active' => true,
            ],
            [
                'name' => 'Sterling Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'insurance@sterlingbank.com',
                'phone' => '+234 1 460 6000',
                'website' => 'https://www.sterlingbank.com',
                'address' => 'Sterling Bank Tower, Plot 209, Adeyemo Alakija Way, Victoria Island, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/213',
                'is_active' => true,
            ],
            [
                'name' => 'Risktec Solutions Ltd',
                'company_type' => 'broker',
                'email' => 'info@risktecng.com',
                'phone' => '+234 1 633 0495',
                'website' => 'https://www.risktecng.com',
                'address' => 'Risktec House, 2nd Floor, T/F, Josel Plaza, Utako District, Abuja',
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/214',
                'is_active' => true,
            ],
            [
                'name' => 'African Alliance Insurance Brokers Ltd',
                'company_type' => 'broker',
                'email' => 'aabr@africanalliance.com',
                'phone' => '+234 1 280 4444',
                'website' => 'https://www.africanalliance.com',
                'address' => 'AAIB House, Plot 2, Block C, Sunbond Layout, Lagos',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/215',
                'is_active' => true,
            ],
            [
                'name' => 'Old Mutual Insurance Brokers Nigeria Ltd',
                'company_type' => 'broker',
                'email' => 'ombn@oldmutual.com.ng',
                'phone' => '+234 1 270 3880',
                'website' => 'https://www.oldmutual.com.ng',
                'address' => 'Old Mutual House, 1-11th Avenue, West Circular Road, Benin City',
                'city' => 'Benin',
                'state' => 'Edo',
                'country' => 'Nigeria',
                'ncrib_reg_number' => 'RN/216',
                'is_active' => true,
            ],
        ];
    }
}
