<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Financial Analytics Report</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; padding: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 3px solid #2E86AB; padding-bottom: 20px; }
        .header h1 { color: #2E86AB; font-size: 24px; margin: 0 0 10px 0; }
        .section { margin-bottom: 25px; }
        .section h3 { color: #2E86AB; font-size: 16px; padding: 10px; background-color: #e3f2fd; border-left: 4px solid #2E86AB; margin: 0 0 15px 0; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #2E86AB; color: white; font-weight: bold; }
        .amount { text-align: right; font-weight: bold; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Financial Analytics Report</h1>
        <p>Generated on {{ $generatedAt }}</p>
        <p>Period: {{ $period }}</p>
    </div>

    <div class="section">
        <h3>Financial Metrics</h3>
        <table>
            <thead>
                <tr><th>Metric</th><th>Value</th></tr>
            </thead>
            <tbody>
                <tr><td>Total Revenue</td><td class="amount">&#8358;{{ number_format($total_revenue ?? 0, 2) }}</td></tr>
                <tr><td>Net Profit</td><td class="amount">&#8358;{{ number_format($net_profit ?? 0, 2) }}</td></tr>
                <tr><td>Loss Ratio</td><td class="amount">{{ number_format($loss_ratio ?? 0, 1) }}%</td></tr>
                <tr><td>Combined Ratio</td><td class="amount">{{ number_format($combined_ratio ?? 0, 1) }}%</td></tr>
                <tr><td>Profit Margin</td><td class="amount">{{ number_format($profit_margin ?? 0, 1) }}%</td></tr>
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>Generated by InsurePal on {{ $generatedAt }}</p>
    </div>
</body>
</html>
