import { NaicomReportStatusBadge } from '@/components/naicom/NaicomReportStatusBadge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import { Head, Link } from '@inertiajs/react';
import { FileBarChart, FileSpreadsheet, Plus, Shield } from 'lucide-react';

interface ReportRun {
    id: number;
    reporting_year: number;
    reporting_half: 'H1' | 'H2';
    status: string;
    generated_by: { id: number; name: string } | null;
    approved_by: { id: number; name: string } | null;
    approved_at: string | null;
    created_at: string;
}

interface PaginatedData {
    data: ReportRun[];
    current_page: number;
    last_page: number;
    total: number;
    from: number;
    to: number;
    links: { url: string | null; label: string; active: boolean }[];
}

interface Props {
    runs: PaginatedData;
}

export default function Index({ runs }: Props) {
    return (
        <AppLayout breadcrumbs={[
            { title: 'Reports', href: route('reports.index') },
            { title: 'NAICOM Returns', href: route('reports.naicom.index') },
        ]}>
            <Head title="NAICOM Returns" />

            <div className="flex flex-col gap-6 p-6">
                <div className="flex items-center justify-between">
                    <div>
                        <h1 className="text-2xl font-bold">NAICOM Returns</h1>
                        <p className="text-sm text-muted-foreground">
                            Forms 7.2A, 7.2B, and 7.2C regulatory reports
                        </p>
                    </div>
                    <Link href={route('reports.naicom.create')}>
                        <Button>
                            <Plus className="mr-2 h-4 w-4" />
                            New Report
                        </Button>
                    </Link>
                </div>

                <Card>
                    <CardHeader>
                        <CardTitle>Report Runs</CardTitle>
                        <CardDescription>
                            All generated NAICOM report runs ({runs.total} total)
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        {runs.data.length === 0 ? (
                            <div className="py-12 text-center">
                                <FileBarChart className="mx-auto mb-4 h-12 w-12 text-muted-foreground" />
                                <p className="mb-2 font-medium">No reports yet</p>
                                <p className="mb-6 text-sm text-muted-foreground">
                                    Generate your first NAICOM compliance report.
                                </p>
                                <Link href={route('reports.naicom.create')}>
                                    <Button>
                                        <FileSpreadsheet className="mr-2 h-4 w-4" />
                                        Create Report
                                    </Button>
                                </Link>
                            </div>
                        ) : (
                            <div className="rounded-md border">
                                <table className="w-full">
                                    <thead>
                                        <tr className="border-b bg-muted/50">
                                            <th className="px-4 py-3 text-left text-sm font-medium">Period</th>
                                            <th className="px-4 py-3 text-left text-sm font-medium">Status</th>
                                            <th className="px-4 py-3 text-left text-sm font-medium">Generated By</th>
                                            <th className="px-4 py-3 text-left text-sm font-medium">Approved By</th>
                                            <th className="px-4 py-3 text-right text-sm font-medium">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {runs.data.map((run) => (
                                            <tr key={run.id} className="border-b last:border-0 hover:bg-muted/50">
                                                <td className="px-4 py-3">
                                                    <div className="flex items-center gap-2">
                                                        <Shield className="h-4 w-4 text-muted-foreground" />
                                                        <div>
                                                            <p className="font-medium">
                                                                {run.reporting_year} {run.reporting_half}
                                                            </p>
                                                            <p className="text-xs text-muted-foreground">
                                                                {new Date(run.created_at).toLocaleDateString()}
                                                            </p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td className="px-4 py-3">
                                                    <NaicomReportStatusBadge status={run.status} />
                                                </td>
                                                <td className="px-4 py-3 text-sm">
                                                    {run.generated_by?.name ?? '—'}
                                                </td>
                                                <td className="px-4 py-3 text-sm">
                                                    {run.approved_by?.name ?? '—'}
                                                </td>
                                                <td className="px-4 py-3 text-right">
                                                    <Link href={route('reports.naicom.show', run.id)}>
                                                        <Button variant="outline" size="sm">View</Button>
                                                    </Link>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
